algorithm: logic
device: cuda:0
env_kwargs: {}
environment: freeway
epochs: 20
eps_clip: 0.2
epsilon_fn: !!python/name:nudge.utils.exp_decay ''
gamma: 0.99
lr_actor: 0.001
lr_critic: 0.0003
max_ep_len: 500
optimizer: !!python/name:torch.optim.adam.Adam ''
recover: false
rules: default
save_steps: 250000
seed: 0
stats_steps: 2000
total_steps: 800001
update_steps: 100
